[package]
name = "pmv-sse"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
image = "0.25.10"
log = "0.4.32"
open_clip_inference = "0.4.0"
ort = "2.0.0-rc.12"
prost = "0.14.4"
sha2 = "0.11.0"
simple_logger = {version = "5.2.0", features = ["stderr"] }
tokio = { version = "1.52.3", features = ["full"] }
tokio-stream = "0.1.18"
tonic = "0.14.6"
tonic-prost = "0.14.6"

[build-dependencies]
tonic-build = "0.14.6"
tonic-prost-build = "0.14.6"
