BackupCopyProgress = "Making backup... ({{.Percent}}%) ({{.Current}} / {{.Total}}) - {{.File}} ({{.PercentFile}}%)"
BackupDone = "Backup done. Total files copied: {{.FileCount}} ({{.Size}})"
BackupDoneReEncrypt = "Backup done. Total files re-encrypted: {{.FileCount}} ({{.Size}})"
BackupFailed = "Backup failed!"
BackupProgress = "Making backup... ({{.Percent}}%) ({{.Current}} / {{.Total}})"
EnterRootPassword = "Enter new password for the root account of the vault ({{.Account}})"
Error = "Error: {{.Message}}"
ErrorCopyFile = "Error copying file {{.File}} | Error: {{.Message}}"
ErrorFetchFile = "Error fetching info of {{.File}} | Error: {{.Message}}"
ErrorNotRegularFile = "{{.File}} is not a regular file"
ErrorPasswordBlank = "Password cannot be blank."
ErrorPasswordNotMatching = "Passwords do not match."
ErrorPasswordTooLong = "Password cannot be longer than 255 characters."
ErrorReEncryptFile = "Error re-encrypting file {{.File}} | Error: {{.Message}}"
ErrorReadPath = "Error reading path {{.Path}} | Error: {{.Message}}"
ExportKeyTitle1 = "Below is is the vault encryption key, in hexadecimal format."
ExportKeyTitle2 = "Make sure to store it securely. Never reveal it!"
ExportKeyTitle3 = "After you are done, press enter to clear the key from view."
FetchNotice = "Fetching metadata from: {{.Path}}"
FindingFiles = "Finding files..."
InitializeNotice = "Initializing backup..."
InitializeProgress = "Initializing backup... ({{.Percent}}%) ({{.Current}} / {{.Total}})"
LoadingCredentials = "Loading credentials..."
LockError = "The destination path has a lock file. Close the vault or remove the vault.lock file."
MakeNotice = "Making backup..."
ModeKeyExport = "Mode: Export encryption key"
ModeKeyRecover = "Mode: Recover encryption key"
ModeReEncryptedBackup = "Mode: Re-encrypted backup"
ModeRegularBackup = "Mode: Regular backup"
PathError = "Path does not exist: {{.Path}}"
ProgramUsage = "Usage: pmv-backup <command> [arguments]"
ProgramUsageBackup = "Usage: pmv-backup backup </path/to/vault> </path/to/backup>"
ProgramUsageBackupTitle = "If you want to create or sync a backup, run the 'backup' command."
ProgramUsageKeyExport = "Usage: pmv-backup key-export </path/to/vault>"
ProgramUsageKeyExportTitle = "If you want to export the encryption key in order to save a backup of it, run the 'key-export' command."
ProgramUsageKeyRecover = "Usage: pmv-backup key-recover </path/to/vault>"
ProgramUsageKeyRecoverTitle = "If you lost access to the vault and you have the encryption key, you can run the 'key-recover' command to restore access."
ProgramUsageReEncrypt = "Usage: pmv-backup re-encrypt </path/to/vault> </path/to/backup>"
ProgramUsageReEncryptTitle = "If you want to re-encrypt the vault with a different encryption key, run the 're-encrypt' command."
ProgramWelcome = "Backup tool for Personal Media Vault."
RecoverKeyDone = "Done! You may now login to the vault with your new password."
RecoverKeyFinalWarning = "WARNING: This will clear all your vault accounts except the root one"
RecoverKeyFinalWarningProceed = "Proceed with key recovery?"
Redacted = "[REDACTED]"
RepeatPassword = "Repeat Password"
VaultCheckingKey = "Checking provided vault key..."
VaultKeyAsk1 = "Input the vault key, in hexadecimal format, and press enter:"
VaultKeyInvalid = "Error: Invalid vault key. Must be a 32 bytes hexadecimal string."
VaultMediaSample = "Sample media asset: [{{.MediaId}}] {{.MediaTitle}}"
VaultNoAlbums = "This vault does not have any albums."
VaultNoMedia = "This vault does not have any media asset."
VaultNoTags = "This vault does not have any tags."
VaultNotFoundError = "Could not find a vault in the specified path"
VaultPrintAlbums = "Vault albums (Total: {{.AlbumCount}}):"
VaultPrintTags = "Vault tags (Total: {{.TagCount}}):"
VaultRecoverKeyProbablyInvalid = "This error means the provided vault key is not valid or the vault is corrupted"
WrongPasswordDestError = "Error: Destination credentials file exists, but password is not the same"
WrongPasswordError = "Error: Wrong password"
YesNo = "y/n"
YesPrefix = "y"
