[BackupCopyProgress]
hash = "sha1-5811f2260d9b0501bc4655803567f53e0fef8599"
other = "Copiando archivos... ({{.Percent}}%) ({{.Current}} / {{.Total}}) - {{.File}} ({{.PercentFile}}%)"

[BackupDone]
hash = "sha1-73f26757f30c3c81ef01a1e448468161b3b79ceb"
other = "Copia de seguridad lista. Total de archivos copiados: {{.FileCount}} ({{.Size}})"

[BackupFailed]
hash = "sha1-c894768353128628d1e2c812a8cdecdb1810f1e4"
other = "¡La copia de seguridad ha fallado!"

[BackupProgress]
hash = "sha1-c3b3202e87a0ab426adcac54587bb902c6a929c1"
other = "Copiando archivos... ({{.Percent}}%) ({{.Current}} / {{.Total}})"

[Error]
hash = "sha1-90033c2be026e065e5abb31b0da67cf8004ca01e"
other = "Error: {{.Message}}"

[ErrorCopyFile]
hash = "sha1-0e6111ea1aa9549bff828bfffaddc0c9232918bd"
other = "Error copiando el archivo {{.File}} | Error: {{.Message}}"

[ErrorFetchFile]
hash = "sha1-316f7aeb0d46593d7ff59e74e970bedc41d924c3"
other = "Error obteniendo información del archivo {{.File}} | Error: {{.Message}}"

[ErrorNotRegularFile]
hash = "sha1-d7badd343243c5bb77627e2e71254cb365bd7a2b"
other = "{{.File}} no es un archivo"

[ErrorReadPath]
hash = "sha1-655a5ae5ba4b1ddfc3dfff44e2f8841ce1e71807"
other = "Error accediendo al directorio {{.Path}} | Error: {{.Message}}"

[FetchNotice]
hash = "sha1-3bf220d0de646037641bfabf6795cdab3c29775e"
other = "Extrayendo metadatos de: {{.Path}}"

[InitializeNotice]
hash = "sha1-c17156c98ada8a559819cf57e5b0997f3b95d995"
other = "Inicializando copia de seguridad..."

[InitializeProgress]
hash = "sha1-aace60c8794b69ff83120922dddf66b98356c98d"
other = "Inicializando copia de seguridad... ({{.Percent}}%) ({{.Current}} / {{.Total}})"

[MakeNotice]
hash = "sha1-aca99d7d39a3215a1e0a3868fd8a9d10989f257d"
other = "Creando copia de seguridad..."

[PathError]
hash = "sha1-9e7a2817625214ec7fc1b0bdd26c5e5b41863a85"
other = "La ruta no existe: {{.Path}}"

[ProgramUsage]
hash = "sha1-1976759ecd4bfc24c7f62b90705229b61c39f942"
other = "Uso del comando: pmv-backup </ruta/de/galería> </ruta/copia/de/seguridad>"

[ProgramWelcome]
hash = "sha1-df69330ffb2a276629bbd93feae80825a052907d"
other = "Herramienta de creación de copias de seguridad de su galería multimedia."

[VaultNotFoundError]
hash = "sha1-f4697133f6137e4d9320d98671bc9eaf8e2a3e91"
other = "No se encontró ninguna galería en la ruta seleccionada"
