BackupCopyProgress = "Making backup... ({{.Percent}}%) ({{.Current}} / {{.Total}}) - {{.File}} ({{.PercentFile}}%)"
BackupDone = "Backup done. Total files copied: {{.FileCount}} ({{.Size}})"
BackupDoneReEncrypt = "Backup done. Total files re-encrypted: {{.FileCount}} ({{.Size}})"
BackupFailed = "Backup failed!"
BackupProgress = "Making backup... ({{.Percent}}%) ({{.Current}} / {{.Total}})"
EnterRootPassword = "Enter root vault account ({{.Account}}) password"
Error = "Error: {{.Message}}"
ErrorCopyFile = "Error copying file {{.File}} | Error: {{.Message}}"
ErrorFetchFile = "Error fetching info of {{.File}} | Error: {{.Message}}"
ErrorNotRegularFile = "{{.File}} is not a regular file"
ErrorReEncryptFile = "Error re-encrypting file {{.File}} | Error: {{.Message}}"
ErrorReadPath = "Error reading path {{.Path}} | Error: {{.Message}}"
FetchNotice = "Fetching metadata from: {{.Path}}"
FindingFiles = "Finding files..."
InitializeNotice = "Initializing backup..."
InitializeProgress = "Initializing backup... ({{.Percent}}%) ({{.Current}} / {{.Total}})"
LoadingCredentials = "Loading credentials..."
LockError = "The destination path has a lock file. Close the vault or remove the vault.lock file."
MakeNotice = "Making backup..."
ModeReEncryptedBackup = "Mode: Re-encrypted backup"
ModeRegularBackup = "Mode: Regular backup"
PathError = "Path does not exist: {{.Path}}"
ProgramUsage = "Usage: pmv-backup <command> [arguments]"
ProgramUsageBackup = "Usage: pmv-backup backup </path/to/vault> </path/to/backup>"
ProgramUsageBackupTitle = "If you want to create or sync a backup, run the 'backup' command."
ProgramUsageReEncrypt = "Usage: pmv-backup re-encrypt </path/to/vault> </path/to/backup>"
ProgramUsageReEncryptTitle = "If you want to re-encrypt the vault with a different encryption key, run the 're-encrypt' command."
ProgramWelcome = "Backup tool for Personal Media Vault."
VaultNotFoundError = "Could not find a vault in the specified path"
WrongPasswordDestError = "Error: Destination credentials file exists, but password is not the same"
WrongPasswordError = "Error: Wrong password"
