BackupCopyProgress = "Making backup... ({{.Percent}}%) ({{.Current}} / {{.Total}}) - {{.File}} ({{.PercentFile}}%)"
BackupDone = "Backup done. Total files copied: {{.FileCount}} ({{.Size}})"
BackupFailed = "Backup failed!"
BackupProgress = "Making backup... ({{.Percent}}%) ({{.Current}} / {{.Total}})"
Error = "Error: {{.Message}}"
ErrorCopyFile = "Error copying file {{.File}} | Error: {{.Message}}"
ErrorFetchFile = "Error fetching info of {{.File}} | Error: {{.Message}}"
ErrorNotRegularFile = "{{.File}} is not a regular file"
ErrorReadPath = "Error reading path {{.Path}} | Error: {{.Message}}"
FetchNotice = "Fetching metadata from: {{.Path}}"
InitializeNotice = "Initializing backup..."
InitializeProgress = "Initializing backup... ({{.Percent}}%) ({{.Current}} / {{.Total}})"
LockError = "The destination path has a lock file. Close the vault or remove the vault.lock file."
MakeNotice = "Making backup..."
PathError = "Path does not exist: {{.Path}}"
ProgramUsage = "Usage: pmv-backup </path/to/vault> </path/to/backup>"
ProgramWelcome = "Backup tool for Personal Media Vault."
VaultNotFoundError = "Could not find a vault in the specified path"
