import { HorizontalBox, Button, VerticalBox, Palette } from "std-widgets.slint";
export component AboutComponent inherits HorizontalBox {
    /// PersonalMediaVault version
    in property <string> version: "1.0.0";

    /// Visit the PersonalMediaVault Website
    callback visit-website();

    /// Visit GitHub page
    callback visit-git();

    alignment: LayoutAlignment.center;
    padding-bottom: 0;
    VerticalBox {
        alignment: LayoutAlignment.center;
        Image {
            source: @image-url("../assets/favicon.png");
            width: 56px;
            height: 56px;
        }
    }

    VerticalBox {
        Text {
            text: @tr("PersonalMediaVault");
            font-size: 14pt;
            font-weight: 800;
        }

        Text {
            text: @tr("Version") + ": " + version;
            font-weight: 600;
        }

        HorizontalBox {
            alignment: LayoutAlignment.start;
            padding: 0;

            Button {
                text: @tr("Visit Website");
                icon: @image-url("../assets/icons/link.svg");
                colorize-icon: true;
                clicked => {
                    root.visit-website();
                }
            }

            Button {
                text: @tr("Visit GitHub");
                icon: @image-url("../assets/icons/link.svg");
                colorize-icon: true;
                clicked => {
                    root.visit-git();
                }
            }
        }
    }
}
