import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 400px;
    height: 400px;
    icon: @image-url("../assets/icon.png");
    title: @tr("PersonalMediaVault Launcher");
    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            primary: true;
            height: 35px;
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
