import { Button, Switch, TextEdit  } from "std-widgets.slint";
import { StringInput } from "string-input.slint";

export component InitialConfigView inherits VerticalLayout {
    /// True if the launcher is busy, meaning the action buttons should be disabled
    in property <bool> busy: false;

    /// Path of the vault
    in property <string> vault-path: "";

    /// Hostname to open browser
    in-out property <string> hostname: "localhost";
    in-out property <bool> hostname-invalid: false;

    /// Listening port
    in-out property <string> port: "8000";
    in-out property <bool> port-invalid: false;

    /// Local listening
    in-out property <bool> listen-local: true;

    /// Back callback
    callback go-back();

    /// Confirm callback
    callback confirm();

    spacing: 1rem;
    padding-top: 2rem;
    padding-left: 1rem;
    padding-right: 1rem;
    alignment: LayoutAlignment.center;

    Text {
        text: @tr("Launcher configuration");
        font-weight: 800;
        font-size: 16pt;
        horizontal-alignment: center;
    }

    Text {
        text: @tr("Configure the daemon to listen on a specific port");
        wrap: TextWrap.word-wrap;
        font-size: 12pt;
        horizontal-alignment: center;
    }

    Text {
        text: @tr("Path") + ": " + vault-path;
        wrap: TextWrap.char-wrap;
        horizontal-alignment: center;
    }

    HorizontalLayout {
        alignment: LayoutAlignment.center;
        padding-top: 0.75rem;

        HorizontalLayout {
            alignment: LayoutAlignment.space-around;

            GridLayout {
                spacing-horizontal: 0.75rem;
                spacing-vertical: 0.25rem;

                Row {
                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        Text {
                            text: @tr("Listening hostname") + ": ";
                            wrap: TextWrap.word-wrap;
                        }
                    }

                    VerticalLayout {
                        alignment: LayoutAlignment.center;

                        StringInput {
                            value <=> root.hostname;
                            read-only: root.busy;
                        }
                    }
                }

                Row {
                    Text {
                        colspan: 2;
                        text: hostname-invalid ? @tr("Invalid hostname") : "";
                        wrap: TextWrap.word-wrap;
                        color: red;
                        font-size: 10pt;
                    }
                }

                Row {
                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        Text {
                            text: @tr("Listening port") + ": ";
                            wrap: TextWrap.word-wrap;
                        }
                    }

                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        StringInput {
                            value <=> root.port;
                            read-only: root.busy;
                            input-type: InputType.number;
                        }
                    }
                }

                Row {
                    Text {
                        colspan: 2;
                        text: port-invalid ? @tr("Invalid port. Must be a number between 1 and 65535") : "";
                        wrap: TextWrap.word-wrap;
                        color: red;
                        font-size: 10pt;
                    }
                }

                Row {
                    Switch {
                        colspan: 2;
                        text: @tr("Listen only on localhost (recommended for local vaults)");
                        checked <=> root.listen-local;
                        enabled: !busy;
                    }
                }
            }
        }
    }

    HorizontalLayout {
        alignment: LayoutAlignment.center;
        padding-top: 0.75rem;
        spacing: 0.75rem;
        Button {
            text: @tr("Back");
            icon: @image-url("../assets/icons/arrow-back.svg");
            colorize-icon: true;
            enabled: !busy;
            clicked => {
                root.go-back();
            }
        }

        Button {
            text: @tr("Continue");
            icon: @image-url("../assets/icons/check.svg");
            primary: true;
            colorize-icon: true;
            enabled: !busy;
            clicked => {
                root.confirm();
            }
        }
    }
}
