import { Button, VerticalBox, HorizontalBox, Palette, ScrollView } from "std-widgets.slint";
import { AboutComponent } from "about.slint";
import { LauncherStatus, FatalErrorType, OpenErrorType } from "status.slint";
import { VaultClosedView } from "vault-closed.slint";
import { OpeningView } from "opening.slint";
import { FatalErrorView } from "fatal-error.slint";
import { OpenErrorView } from "open-error.slint";
import { CreateAskView } from "create-ask.slint";
import { LockAskView } from "lock-ask.slint";

export { LauncherStatus, FatalErrorType, OpenErrorType }

export component MainWindow inherits Window {
    icon: @image-url("../assets/favicon.png");
    title: @tr("PersonalMediaVault Launcher");

    /// The general status of the launcher
    in-out property <LauncherStatus> launcher-status: closed;

    /// Path of the vault
    in property <string> vault-path: "";

    preferred-width: 640px;
    preferred-height: 480px;

    /// PersonalMediaVault version
    in property <string> version: "1.0.0";

    /// Visit the PersonalMediaVault Website
    callback visit-website();

    /// Visit GitHub page
    callback visit-git();

    /// Close callback
    callback close-launcher();

    /// True if the launcher is busy, meaning the action buttons should be disabled
    in property <bool> busy: false;

    /// Type of fatal error that occurred
    in property <FatalErrorType> fatal-error-type: unknown;

    /// Type of open error that occurred
    in property <OpenErrorType> open-error-type: unknown;

    /// Select a folder and open the vault store there
    callback open-vault-folder();

    /// Open the default vault, located in the user's home folder
    callback open-default-vault();

    /// Create the folder and open it
    callback create-folder-and-open();

    /// Forcefully open the vault (locked)
    callback force-open();

    VerticalBox {
        AboutComponent {
            version: version;
            visit-website => {
                root.visit-website();
            }
            visit-git => {
                root.visit-git();
            }
        }

        Rectangle {
            border-width: 0;
            height: 1px;
            background: Palette.border;
        }

        VerticalLayout {
            if(launcher-status == LauncherStatus.closed): VaultClosedView {
                busy: busy;
                open-default-vault => {
                    root.open-default-vault();
                }
                open-vault-folder => {
                    root.open-vault-folder();
                }
            }

            if(launcher-status == LauncherStatus.fatal-error): FatalErrorView {
                fatal-error-type: fatal-error-type;
                close-launcher => {
                    root.close-launcher();
                }
            }

            if(launcher-status == LauncherStatus.opening): OpeningView {
                vault-path: vault-path;
            }

            if(launcher-status == LauncherStatus.open-error): OpenErrorView {
                open-error-type: open-error-type;
                vault-path: vault-path;
                go-back => {
                    root.launcher-status = LauncherStatus.closed;
                }
            }

            if(launcher-status == LauncherStatus.create-ask): CreateAskView {
                vault-path: vault-path;
                confirm => {
                    root.create-folder-and-open();
                }
                go-back => {
                    root.launcher-status = LauncherStatus.closed;
                }
            }

            if(launcher-status == LauncherStatus.lock-ask): LockAskView {
                vault-path: vault-path;
                confirm => {
                    root.force-open();
                }
                go-back => {
                    root.launcher-status = LauncherStatus.closed;
                }
            }
        }
    }
}
