
// Status of the launcher
export enum LauncherStatus { closed, fatal-error, opening, open-error, create-ask, lock-ask, initial-config, create-vault-ask, open}

// Type of fatal error
export enum FatalErrorType { unknown, daemon-missing, frontend-missing, ffmpeg-missing, ffprobe-missing }

// Type of open error
export enum OpenErrorType { unknown, create-folder-error, lock-error, save-config-error, init-error }

// Status of the daemon
export enum VaultDaemonStatus { stopped, starting, running, stopping, error }

// Type of daemon error
export enum VaultDaemonErrorType { unknown, lock, port-in-use, invalid-ssl }
