import { Button, TabWidget } from "std-widgets.slint";
import { VaultStatusView } from "vault-status.slint";
import { VaultDaemonStatus, VaultDaemonErrorType, VaultToolStatus, VaultSelectedTool } from "status.slint";
import { VaultConfigView } from "vault-config.slint";
import { VaultToolsView } from "vault-tools.slint";

export component VaultOpenView inherits VerticalLayout {
    /// True if the launcher is busy, meaning the action buttons should be disabled
    in property <bool> busy: false;

    /// Path of the vault
    in property <string> vault-path: "";

    /// Status of the vault daemon
    in property <VaultDaemonStatus> daemon-status: VaultDaemonStatus.stopped;

    /// Daemon error type
    in property <VaultDaemonErrorType> daemon-error-type: VaultDaemonErrorType.unknown;

    /// Daemon error details
    in property <string> daemon-error-details: "";

    /// Start callback
    callback start();

    /// Stop callback
    callback stop();

    /// Restart callback
    callback restart();

    /// Open browser callback
    callback open-browser();

    /// Open log callback
    callback open-log();

    /// Callback to reset the config
    callback reset-config();

    /// Hostname to open browser
    in-out property <string> hostname: "localhost";
    in-out property <bool> hostname-invalid: false;

    /// Listening port
    in-out property <string> port: "8000";
    in-out property <bool> port-invalid: false;

    /// Local listening
    in-out property <bool> listen-local: true;

    // Dirty and saved for host-port
    in-out property <bool> dirty-host-port: false;
    in-out property <bool> saved-host-port: false;

    /// Callback to update the host and port config
    callback update-port-host();

    /// TLS certificate
    in-out property <string> tls-cert: "";
    in-out property <bool> tls-cert-invalid: false;

    /// Callback to select certificate file
    callback select-tls-cert();

    /// TLS key
    in-out property <string> tls-key: "";
    in-out property <bool> tls-key-invalid: false;

    /// Callback to select certificate file
    callback select-tls-key();

    /// TLS enabled
    in-out property <bool> tls-enabled: true;

    // Dirty and saved for TLS
    in-out property <bool> dirty-tls: false;
    in-out property <bool> saved-tls: false;

    /// Callback to update the TLS config
    callback update-tls();

    /// FFmpeg binary
    in-out property <string> ffmpeg-path: "";
    in-out property <bool> ffmpeg-path-invalid: false;

    /// Callback to select the ffmpeg binary
    callback select-ffmpeg-path();

    /// FFprobe binary
    in-out property <string> ffprobe-path: "";
    in-out property <bool> ffprobe-path-invalid: false;

    /// Callback to select the ffprobe binary
    callback select-ffprobe-path();

    in-out property <string> video-codec: "";
    in-out property <bool> video-codec-invalid: false;

    // Dirty and saved for FFmpeg
    in-out property <bool> dirty-ffmpeg: false;
    in-out property <bool> saved-ffmpeg: false;

    /// Callback to update the FFMpeg config
    callback update-ffmpeg();

    /// Cache size
    in-out property <string> cache-size: "1024";
    in-out property <bool> cache-size-invalid: false;

    /// Request logging
    in-out property <bool> log-requests: false;

    /// Debug logging
    in-out property <bool> log-debug: false;

    // Dirty and saved for other
    in-out property <bool> dirty-other: false;
    in-out property <bool> saved-other: false;

    /// Callback to update the rest of config values
    callback update-other();

    /// The status of the tool
    in-out property <VaultToolStatus> tool-status: VaultToolStatus.idle;

    /// Error of the tool
    in property <string> tool-error: "";

    /// Run the selected tool
    callback run-tool(VaultSelectedTool);

    /// Cancel the tool that is running
    callback cancel-tool();

    spacing: 0.75rem;
    alignment: LayoutAlignment.start;

    Text {
        text: @tr("Path") + ": " + vault-path;
        wrap: TextWrap.char-wrap;
        horizontal-alignment: center;
    }

    TabWidget {
        Tab {
            title: @tr("Status");
            VaultStatusView {
                busy: busy || tool-status == VaultToolStatus.running;
                daemon-status: daemon-status;
                daemon-error-type: daemon-error-type;
                daemon-error-details: daemon-error-details;
                start => {
                    root.start();
                }
                stop => {
                    root.stop();
                }
                restart => {
                    root.restart();
                }
                open-browser => {
                    root.open-browser();
                }
                open-log => {
                    root.open-log();
                }
            }
        }

        Tab {
            title: @tr("Configuration");
            VaultConfigView {
                busy: busy || tool-status == VaultToolStatus.running;

                hostname <=> root.hostname;
                hostname-invalid <=> root.hostname-invalid;
                port <=> root.port;
                port-invalid <=> root.port-invalid;
                listen-local <=> root.listen-local;
                dirty-host-port <=> root.dirty-host-port;
                saved-host-port <=> root.saved-host-port;

                tls-enabled <=> tls-enabled;
                tls-cert <=> tls-cert;
                tls-cert-invalid <=> tls-cert-invalid;
                tls-key <=> tls-key;
                tls-key-invalid <=> tls-cert-invalid;
                dirty-tls <=> root.dirty-tls;
                saved-tls <=> root.saved-tls;

                ffmpeg-path <=> ffmpeg-path;
                ffmpeg-path-invalid <=> ffmpeg-path-invalid;
                ffprobe-path <=> ffprobe-path;
                ffprobe-path-invalid <=> ffprobe-path-invalid;
                video-codec <=> video-codec;
                video-codec-invalid <=> video-codec-invalid;
                dirty-ffmpeg <=> root.dirty-ffmpeg;
                saved-ffmpeg <=> root.saved-ffmpeg;

                cache-size <=> root.cache-size;
                cache-size-invalid <=> root.cache-size-invalid;
                log-requests <=> root.log-requests;
                log-debug <=> root.log-debug;
                dirty-other <=> root.dirty-other;
                saved-other <=> root.saved-other;

                select-tls-cert => {
                    root.select-tls-cert();
                }
                select-tls-key => {
                    root.select-tls-key();
                }
                select-ffmpeg-path => {
                    root.select-ffmpeg-path();
                }
                select-ffprobe-path => {
                    root.select-ffprobe-path();
                }
                reset-config => {
                    root.reset-config();
                }
                update-port-host => {
                    root.update-port-host();
                }
                update-tls => {
                    root.update-tls();
                }
                update-ffmpeg => {
                    root.update-ffmpeg();
                }
                update-other => {
                    root.update-other();
                }
            }
        }

        Tab {
            title: @tr("Backup");
            Text {
                text: "TODO";
            }
        }

        Tab {
            title: @tr("Other Tools");
            VaultToolsView {
                busy: busy;

                tool-status <=> tool-status;
                tool-error: tool-error;

                run-tool(t) => {
                    root.run-tool(t);
                }

                cancel-tool => {
                    root.cancel-tool();
                }
            }
        }
    }
}
