
import { StringInput } from "string-input.slint";
import { Switch, Button } from "std-widgets.slint";

export component VaultConfigSseView inherits VerticalLayout {
    /// True if the launcher is busy, meaning the action buttons should be disabled
    in property <bool> busy: false;

    /// SSE enabled?
    in-out property <bool> sse-enabled: false;

    /// Model path
    in-out property <string> model-path: "";
    in-out property <bool> model-path-invalid: false;
    in-out property <string> model-path-missing-file: "";

    /// Callback to select the model path
    callback select-model-path();

    /// Max size for images (MB)
    in-out property <string> img-max-size: "1024";
    in-out property <bool> img-max-size-invalid: false;

    /// Dirty and saved
    in-out property <bool> dirty: false;
    in-out property <bool> saved: false;

    /// Save callback
    callback save();

    spacing: 1rem;
    padding-top: 1rem;
    padding-left: 1rem;
    padding-right: 1rem;
    alignment: LayoutAlignment.start;

    HorizontalLayout {
        alignment: LayoutAlignment.center;
        padding-top: 0.75rem;

        HorizontalLayout {
            alignment: LayoutAlignment.space-around;

            GridLayout {
                spacing-horizontal: 0.75rem;
                spacing-vertical: 0.25rem;

                Row {
                    Switch {
                        colspan: 3;
                        text: @tr("Enable semantic search for the vault");
                        checked <=> root.sse-enabled;
                        enabled: !busy;
                        changed checked => {
                            root.dirty = true;
                            root.saved = false;
                        }
                    }
                }

                Row {
                    Text {
                        colspan: 2;
                        text: "";
                        wrap: TextWrap.word-wrap;
                        color: red;
                        font-size: 10pt;
                    }
                }

                Row {
                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        Text {
                            text: @tr("OpenCLIP model path") + ": ";
                            wrap: TextWrap.word-wrap;
                        }
                    }

                    VerticalLayout {
                        alignment: LayoutAlignment.center;

                        StringInput {
                            value <=> root.model-path;
                            read-only: root.busy || !sse-enabled;
                            changed value => {
                                root.dirty = true;
                                root.saved = false;
                            }
                        }
                    }

                    VerticalLayout {
                        alignment: LayoutAlignment.center;

                        Button {
                            text: @tr("Find");
                            icon: @image-url("../assets/icons/folder-open.svg");
                            colorize-icon: true;
                            enabled: !busy && sse-enabled;
                            clicked => {
                                root.select-model-path();
                            }
                        }
                    }
                }

                Row {
                    Text {
                        colspan: 3;
                        text: model-path-invalid ?
                            (model-path-missing-file != "" ?
                            (@tr("Invalid OpenCLIP model: Missing file") + ": " + model-path-missing-file) :
                            @tr("Invalid OpenCLIP model: Folder not found")) : "";
                        wrap: TextWrap.word-wrap;
                        color: red;
                        font-size: 10pt;
                    }
                }

                Row {
                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        Text {
                            text: @tr("Max size for images (MB)") + ": ";
                            wrap: TextWrap.word-wrap;
                        }
                    }

                    VerticalLayout {
                        alignment: LayoutAlignment.center;
                        StringInput {
                            value <=> root.img-max-size;
                            read-only: root.busy;
                            input-type: InputType.number;
                            changed value => {
                                root.dirty = true;
                                root.saved = false;
                            }
                        }
                    }
                }

                Row {
                    Text {
                        colspan: 2;
                        text: img-max-size-invalid ? @tr("Invalid max size. Must be a number greater or equal to 0.") : "";
                        wrap: TextWrap.word-wrap;
                        color: red;
                        font-size: 10pt;
                    }
                }
            }
        }
    }

    HorizontalLayout {
        alignment: LayoutAlignment.center;
        padding-top: 0.75rem;
        spacing: 0.75rem;

        Button {
            text: @tr("Apply changes");
            icon: @image-url("../assets/icons/check.svg");
            primary: true;
            colorize-icon: true;
            enabled: !busy && dirty;
            clicked => {
                root.save();
            }
        }
    }

    if saved: HorizontalLayout {
        Text {
            text: @tr("Configuration changes successfully saved!");
            wrap: TextWrap.word-wrap;
            horizontal-alignment: center;
            color: green;
        }
    }
}
