

import { TabWidget } from "std-widgets.slint";
import { VaultConfigHostPortView } from "vault-config-host-port.slint";
import { VaultConfigOtherView } from "vault-config-other.slint";
import { VaultConfigTlsView } from "vault-config-tls.slint";
import { VaultConfigFFmpegView } from "vault-config-ffmpeg.slint";

export component VaultConfigView inherits VerticalLayout {
    /// True if the launcher is busy, meaning the action buttons should be disabled
    in property <bool> busy: false;

    /// Callback to reset the config
    callback reset-config();

    /// Hostname to open browser
    in-out property <string> hostname: "localhost";
    in-out property <bool> hostname-invalid: false;

    /// Listening port
    in-out property <string> port: "8000";
    in-out property <bool> port-invalid: false;

    /// Local listening
    in-out property <bool> listen-local: true;

    // Dirty and saved for host-port
    in-out property <bool> dirty-host-port: false;
    in-out property <bool> saved-host-port: false;

    /// Callback to update the host and port config
    callback update-port-host();

    /// TLS certificate
    in-out property <string> tls-cert: "";
    in-out property <bool> tls-cert-invalid: false;

    /// Callback to select certificate file
    callback select-tls-cert();

    /// TLS key
    in-out property <string> tls-key: "";
    in-out property <bool> tls-key-invalid: false;

    /// Callback to select certificate file
    callback select-tls-key();

    /// TLS enabled
    in-out property <bool> tls-enabled: true;

    // Dirty and saved for TLS
    in-out property <bool> dirty-tls: false;
    in-out property <bool> saved-tls: false;

    /// Callback to update the TLS config
    callback update-tls();

     /// FFmpeg binary
    in-out property <string> ffmpeg-path: "";
    in-out property <bool> ffmpeg-path-invalid: false;

    /// Callback to select the ffmpeg binary
    callback select-ffmpeg-path();

    /// FFprobe binary
    in-out property <string> ffprobe-path: "";
    in-out property <bool> ffprobe-path-invalid: false;

    /// Callback to select the ffprobe binary
    callback select-ffprobe-path();

    in-out property <string> video-codec: "";
    in-out property <bool> video-codec-invalid: false;

    // Dirty and saved for FFmpeg
    in-out property <bool> dirty-ffmpeg: false;
    in-out property <bool> saved-ffmpeg: false;

    /// Callback to update the FFMpeg config
    callback update-ffmpeg();

    /// Cache size
    in-out property <string> cache-size: "1024";
    in-out property <bool> cache-size-invalid: false;

    /// Request logging
    in-out property <bool> log-requests: false;

    /// Debug logging
    in-out property <bool> log-debug: false;

    // Dirty and saved for other
    in-out property <bool> dirty-other: false;
    in-out property <bool> saved-other: false;

    /// Callback to update the rest of config values
    callback update-other();

    padding-top: 1rem;
    spacing: 1rem;
    alignment: LayoutAlignment.start;

    Text {
        text: @tr("Vault configuration");
        wrap: TextWrap.char-wrap;
        horizontal-alignment: center;
        font-size: 12pt;
        font-weight: 800;
    }

    TabWidget {
        changed current-index => {
            root.reset-config();
        }

        Tab {
            title: @tr("Host & Port");
            VaultConfigHostPortView {
                busy: busy;
                hostname <=> root.hostname;
                hostname-invalid <=> root.hostname-invalid;
                port <=> root.port;
                port-invalid <=> root.port-invalid;
                listen-local <=> root.listen-local;
                dirty <=> root.dirty-host-port;
                saved <=> root.saved-host-port;
                save => {
                    root.update-port-host();
                }
            }
        }

        Tab {
            title: @tr("TLS");
            VaultConfigTlsView {
                busy: busy;
                tls-enabled <=> tls-enabled;
                tls-cert <=> tls-cert;
                tls-cert-invalid <=> tls-cert-invalid;
                tls-key <=> tls-key;
                tls-key-invalid <=> tls-cert-invalid;
                dirty <=> dirty-tls;
                saved <=> saved-tls;
                select-tls-cert => {
                    root.select-tls-cert();
                }
                select-tls-key => {
                    root.select-tls-key();
                }
                save => {
                    root.update-tls();
                }
            }
        }

        Tab {
            title: @tr("FFmpeg");
            VaultConfigFFmpegView {
                busy: busy;
                ffmpeg-path <=> ffmpeg-path;
                ffmpeg-path-invalid <=> ffmpeg-path-invalid;
                ffprobe-path <=> ffprobe-path;
                ffprobe-path-invalid <=> ffprobe-path-invalid;
                video-codec <=> video-codec;
                video-codec-invalid <=> video-codec-invalid;
                dirty <=> dirty-ffmpeg;
                saved <=> saved-ffmpeg;
                select-ffmpeg-path => {
                    root.select-ffmpeg-path();
                }
                select-ffprobe-path => {
                    root.select-ffprobe-path();
                }
                save => {
                    root.update-ffmpeg();
                }
            }
        }

        Tab {
            title: @tr("Other");
            VaultConfigOtherView {
                busy: busy;
                cache-size <=> root.cache-size;
                cache-size-invalid <=> root.cache-size-invalid;
                log-requests <=> root.log-requests;
                log-debug <=> root.log-debug;
                dirty <=> dirty-other;
                saved <=> saved-other;
                save => {
                    root.update-other();
                }
            }
        }
    }
}
