import { Button, TabWidget } from "std-widgets.slint";
import { VaultStatusView } from "vault-status.slint";
import {
    VaultDaemonStatus,
    VaultDaemonErrorType,
    VaultToolStatus,
    VaultSelectedBackupOption,
    VaultBackupStatus,
    VaultBackupCurrentTask,
    VaultBackupErrorType,
    VaultSelectedTool,
} from "status.slint";
import { VaultConfigView } from "vault-config.slint";
import { VaultBackupView } from "vault-backup.slint";
import { VaultToolsView } from "vault-tools.slint";

export component VaultOpenView inherits VerticalLayout {
    /// True if the launcher is busy, meaning the action buttons should be disabled
    in property <bool> busy: false;

    /// Path of the vault
    in property <string> vault-path: "";

    /// Status of the vault daemon
    in property <VaultDaemonStatus> daemon-status: VaultDaemonStatus.stopped;

    /// Daemon error type
    in property <VaultDaemonErrorType> daemon-error-type: VaultDaemonErrorType.unknown;

    /// Daemon error details
    in property <string> daemon-error-details: "";

    /// Start callback
    callback start();

    /// Stop callback
    callback stop();

    /// Restart callback
    callback restart();

    /// Open browser callback
    callback open-browser();

    /// Open log callback
    callback open-log();

    /// Callback to reset the config
    callback reset-config();

    /// Hostname to open browser
    in-out property <string> hostname: "localhost";
    in-out property <bool> hostname-invalid: false;

    /// Listening port
    in-out property <string> port: "8000";
    in-out property <bool> port-invalid: false;

    /// Local listening
    in-out property <bool> listen-local: true;

    // Dirty and saved for host-port
    in-out property <bool> dirty-host-port: false;
    in-out property <bool> saved-host-port: false;

    /// Callback to update the host and port config
    callback update-port-host();

    /// TLS certificate
    in-out property <string> tls-cert: "";
    in-out property <bool> tls-cert-invalid: false;

    /// Callback to select certificate file
    callback select-tls-cert();

    /// TLS key
    in-out property <string> tls-key: "";
    in-out property <bool> tls-key-invalid: false;

    /// Callback to select certificate file
    callback select-tls-key();

    /// TLS enabled
    in-out property <bool> tls-enabled: true;

    // Dirty and saved for TLS
    in-out property <bool> dirty-tls: false;
    in-out property <bool> saved-tls: false;

    /// Callback to update the TLS config
    callback update-tls();

    /// FFmpeg binary
    in-out property <string> ffmpeg-path: "";
    in-out property <bool> ffmpeg-path-invalid: false;

    /// Callback to select the ffmpeg binary
    callback select-ffmpeg-path();

    /// FFprobe binary
    in-out property <string> ffprobe-path: "";
    in-out property <bool> ffprobe-path-invalid: false;

    /// Callback to select the ffprobe binary
    callback select-ffprobe-path();

    in-out property <string> video-codec: "";
    in-out property <bool> video-codec-invalid: false;

    // Dirty and saved for FFmpeg
    in-out property <bool> dirty-ffmpeg: false;
    in-out property <bool> saved-ffmpeg: false;

    /// Callback to update the FFMpeg config
    callback update-ffmpeg();

    /// Cache size
    in-out property <string> cache-size: "1024";
    in-out property <bool> cache-size-invalid: false;

    /// Request logging
    in-out property <bool> log-requests: false;

    /// Debug logging
    in-out property <bool> log-debug: false;

    // Dirty and saved for other
    in-out property <bool> dirty-other: false;
    in-out property <bool> saved-other: false;

    /// Callback to update the rest of config values
    callback update-other();

    /// The status of the backup
    in-out property <VaultBackupStatus> backup-status: VaultBackupStatus.idle;

    /// The current task of the backup
    in-out property <VaultBackupCurrentTask> backup-task: VaultBackupCurrentTask.none;

    /// Vault encryption key
    in-out property <string> encryption-key: "";
    in-out property <bool> encryption-key-invalid: false;

    /// Error type of the backup
    in property <VaultBackupErrorType> backup-error-type: VaultBackupErrorType.unknown;

    /// Error of the backup
    in property <string> backup-error: "";

    /// Progress of the backup
    in property <float> backup-progress: 0;

    /// True if the progress is indeterminate
    in property <bool> backup-progress-indeterminate: true;

    /// Global progress
    in property <string> backup-progress-global: "";

    /// Current file progress
    in property <string> backup-progress-file: "";

    // Backup path
    in-out property <string> backup-path: "";
    in-out property <bool> backup-path-invalid: false;

    /// Username input
    in-out property <string> username: "";
    in-out property <bool> username-invalid: false;

    /// Password input
    in-out property <string> password: "";
    in-out property <bool> password-invalid: false;

    /// Password input (repeat)
    in-out property <string> password-repeat: "";
    in-out property <bool> password-repeat-invalid: false;

    /// Result of the backup
    in property <string> backup-result-files: "0";
    in property <string> backup-result-bytes: "0 B";

    /// Run the selected tool
    callback run-backup(VaultSelectedBackupOption);

    /// Cancel the backup process
    callback cancel-backup();

    /// Callback to select backup path
    callback select-backup-path();

    /// Callback to copy the encryption key to clipboard
    callback copy-encryption-key();

    /// The status of the tool
    in-out property <VaultToolStatus> tool-status: VaultToolStatus.idle;

    /// Error of the tool
    in property <string> tool-error: "";

    /// Run the selected tool
    callback run-tool(VaultSelectedTool);

    /// Cancel the tool that is running
    callback cancel-tool();

    spacing: 0.75rem;
    alignment: LayoutAlignment.start;

    Text {
        text: @tr("Path") + ": " + vault-path;
        wrap: TextWrap.char-wrap;
        horizontal-alignment: center;
    }

    TabWidget {
        Tab {
            title: @tr("Status");
            VaultStatusView {
                busy: busy || tool-status == VaultToolStatus.running || backup-status == VaultBackupStatus.running;
                daemon-status: daemon-status;
                daemon-error-type: daemon-error-type;
                daemon-error-details: daemon-error-details;
                start => {
                    root.start();
                }
                stop => {
                    root.stop();
                }
                restart => {
                    root.restart();
                }
                open-browser => {
                    root.open-browser();
                }
                open-log => {
                    root.open-log();
                }
            }
        }

        Tab {
            title: @tr("Configuration");
            VaultConfigView {
                busy: busy || tool-status == VaultToolStatus.running || backup-status == VaultBackupStatus.running;

                hostname <=> root.hostname;
                hostname-invalid <=> root.hostname-invalid;
                port <=> root.port;
                port-invalid <=> root.port-invalid;
                listen-local <=> root.listen-local;
                dirty-host-port <=> root.dirty-host-port;
                saved-host-port <=> root.saved-host-port;

                tls-enabled <=> tls-enabled;
                tls-cert <=> tls-cert;
                tls-cert-invalid <=> tls-cert-invalid;
                tls-key <=> tls-key;
                tls-key-invalid <=> tls-cert-invalid;
                dirty-tls <=> root.dirty-tls;
                saved-tls <=> root.saved-tls;

                ffmpeg-path <=> ffmpeg-path;
                ffmpeg-path-invalid <=> ffmpeg-path-invalid;
                ffprobe-path <=> ffprobe-path;
                ffprobe-path-invalid <=> ffprobe-path-invalid;
                video-codec <=> video-codec;
                video-codec-invalid <=> video-codec-invalid;
                dirty-ffmpeg <=> root.dirty-ffmpeg;
                saved-ffmpeg <=> root.saved-ffmpeg;

                cache-size <=> root.cache-size;
                cache-size-invalid <=> root.cache-size-invalid;
                log-requests <=> root.log-requests;
                log-debug <=> root.log-debug;
                dirty-other <=> root.dirty-other;
                saved-other <=> root.saved-other;

                select-tls-cert => {
                    root.select-tls-cert();
                }
                select-tls-key => {
                    root.select-tls-key();
                }
                select-ffmpeg-path => {
                    root.select-ffmpeg-path();
                }
                select-ffprobe-path => {
                    root.select-ffprobe-path();
                }
                reset-config => {
                    root.reset-config();
                }
                update-port-host => {
                    root.update-port-host();
                }
                update-tls => {
                    root.update-tls();
                }
                update-ffmpeg => {
                    root.update-ffmpeg();
                }
                update-other => {
                    root.update-other();
                }
            }
        }

        Tab {
            title: @tr("Backup");
            VaultBackupView {
                busy: busy || tool-status == VaultToolStatus.running;

                backup-status <=> backup-status;
                
                backup-path <=> backup-path;
                backup-path-invalid <=> backup-path-invalid;
                encryption-key <=> encryption-key;
                encryption-key-invalid <=> encryption-key-invalid;
                username <=> username;
                username-invalid <=> username-invalid;
                password <=> password;
                password-invalid <=> password-invalid;
                password-repeat <=> password-repeat;
                password-repeat-invalid <=> password-repeat-invalid;

                backup-error: backup-error;
                backup-error-type: backup-error-type;

                backup-task <=> backup-task;
                backup-progress: backup-progress;
                backup-progress-indeterminate: backup-progress-indeterminate;
                backup-progress-global: backup-progress-global;
                backup-progress-file: backup-progress-file;

                backup-result-files: backup-result-files;
                backup-result-bytes: backup-result-bytes;

                run-backup(t) => {
                    root.run-backup(t);
                }

                cancel-backup => {
                    root.cancel-backup();
                }

                select-backup-path => {
                    root.select-backup-path();
                }

                copy-encryption-key => {
                    root.copy-encryption-key();
                }
            }
        }

        Tab {
            title: @tr("Other Tools");
            VaultToolsView {
                busy: busy || backup-status == VaultBackupStatus.running;

                tool-status <=> tool-status;
                tool-error: tool-error;
                username <=> username;
                password <=> password;

                run-tool(t) => {
                    root.run-tool(t);
                }

                cancel-tool => {
                    root.cancel-tool();
                }
            }
        }
    }
}
