// Semantic Search Engine Protocol

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: sse.proto

package sse_proto_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for the model metadata
type ClipModelMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// API key to access the service
	ApiKey        string `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipModelMetadataRequest) Reset() {
	*x = ClipModelMetadataRequest{}
	mi := &file_sse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipModelMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipModelMetadataRequest) ProtoMessage() {}

func (x *ClipModelMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipModelMetadataRequest.ProtoReflect.Descriptor instead.
func (*ClipModelMetadataRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{0}
}

func (x *ClipModelMetadataRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Response with the model metadata
type ClipModelMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of dimensions for embedding vectors
	EmbedDim      uint32 `protobuf:"varint,2,opt,name=embed_dim,json=embedDim,proto3" json:"embed_dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipModelMetadataResponse) Reset() {
	*x = ClipModelMetadataResponse{}
	mi := &file_sse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipModelMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipModelMetadataResponse) ProtoMessage() {}

func (x *ClipModelMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipModelMetadataResponse.ProtoReflect.Descriptor instead.
func (*ClipModelMetadataResponse) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{1}
}

func (x *ClipModelMetadataResponse) GetEmbedDim() uint32 {
	if x != nil {
		return x.EmbedDim
	}
	return 0
}

// A response with an embedding
type ClipEmbeddingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of features of the resulting vector
	Features      []float32 `protobuf:"fixed32,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipEmbeddingResponse) Reset() {
	*x = ClipEmbeddingResponse{}
	mi := &file_sse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipEmbeddingResponse) ProtoMessage() {}

func (x *ClipEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*ClipEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{2}
}

func (x *ClipEmbeddingResponse) GetFeatures() []float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

// Request for text embedding
type ClipTextEmbeddingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text to be embedded into a vector
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// API key to access the service
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipTextEmbeddingRequest) Reset() {
	*x = ClipTextEmbeddingRequest{}
	mi := &file_sse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipTextEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipTextEmbeddingRequest) ProtoMessage() {}

func (x *ClipTextEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipTextEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*ClipTextEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{3}
}

func (x *ClipTextEmbeddingRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ClipTextEmbeddingRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Initialization message for image embedding
type ClipImageEmbeddingRequestInit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Image mime type. Example: image/png
	MimeType string `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// API key to access the service
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipImageEmbeddingRequestInit) Reset() {
	*x = ClipImageEmbeddingRequestInit{}
	mi := &file_sse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipImageEmbeddingRequestInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipImageEmbeddingRequestInit) ProtoMessage() {}

func (x *ClipImageEmbeddingRequestInit) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipImageEmbeddingRequestInit.ProtoReflect.Descriptor instead.
func (*ClipImageEmbeddingRequestInit) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{4}
}

func (x *ClipImageEmbeddingRequestInit) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ClipImageEmbeddingRequestInit) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Chunk message for image embedding
type ClipImageEmbeddingRequestChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Part of the bytes of the image
	ImageChunk    []byte `protobuf:"bytes,1,opt,name=image_chunk,json=imageChunk,proto3" json:"image_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipImageEmbeddingRequestChunk) Reset() {
	*x = ClipImageEmbeddingRequestChunk{}
	mi := &file_sse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipImageEmbeddingRequestChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipImageEmbeddingRequestChunk) ProtoMessage() {}

func (x *ClipImageEmbeddingRequestChunk) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipImageEmbeddingRequestChunk.ProtoReflect.Descriptor instead.
func (*ClipImageEmbeddingRequestChunk) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{5}
}

func (x *ClipImageEmbeddingRequestChunk) GetImageChunk() []byte {
	if x != nil {
		return x.ImageChunk
	}
	return nil
}

// Request for image embedding
type ClipImageEmbeddingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ImageEmbeddingOneof:
	//
	//	*ClipImageEmbeddingRequest_Init
	//	*ClipImageEmbeddingRequest_Chunk
	ImageEmbeddingOneof isClipImageEmbeddingRequest_ImageEmbeddingOneof `protobuf_oneof:"image_embedding_oneof"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ClipImageEmbeddingRequest) Reset() {
	*x = ClipImageEmbeddingRequest{}
	mi := &file_sse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipImageEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipImageEmbeddingRequest) ProtoMessage() {}

func (x *ClipImageEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipImageEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*ClipImageEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{6}
}

func (x *ClipImageEmbeddingRequest) GetImageEmbeddingOneof() isClipImageEmbeddingRequest_ImageEmbeddingOneof {
	if x != nil {
		return x.ImageEmbeddingOneof
	}
	return nil
}

func (x *ClipImageEmbeddingRequest) GetInit() *ClipImageEmbeddingRequestInit {
	if x != nil {
		if x, ok := x.ImageEmbeddingOneof.(*ClipImageEmbeddingRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *ClipImageEmbeddingRequest) GetChunk() *ClipImageEmbeddingRequestChunk {
	if x != nil {
		if x, ok := x.ImageEmbeddingOneof.(*ClipImageEmbeddingRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isClipImageEmbeddingRequest_ImageEmbeddingOneof interface {
	isClipImageEmbeddingRequest_ImageEmbeddingOneof()
}

type ClipImageEmbeddingRequest_Init struct {
	// Init message (sent as the first message of the stream)
	Init *ClipImageEmbeddingRequestInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type ClipImageEmbeddingRequest_Chunk struct {
	// Chunk message (send chunks of 2MB max with the image bytes in order)
	Chunk *ClipImageEmbeddingRequestChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*ClipImageEmbeddingRequest_Init) isClipImageEmbeddingRequest_ImageEmbeddingOneof() {}

func (*ClipImageEmbeddingRequest_Chunk) isClipImageEmbeddingRequest_ImageEmbeddingOneof() {}

// Request to get vectors by media resource
type GetVectorsByMediaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the media resource
	MediaId uint64 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	// API key to access the service
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVectorsByMediaRequest) Reset() {
	*x = GetVectorsByMediaRequest{}
	mi := &file_sse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVectorsByMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVectorsByMediaRequest) ProtoMessage() {}

func (x *GetVectorsByMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVectorsByMediaRequest.ProtoReflect.Descriptor instead.
func (*GetVectorsByMediaRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{7}
}

func (x *GetVectorsByMediaRequest) GetMediaId() uint64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *GetVectorsByMediaRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Request to query vectors
type QueryVectorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Embedding features
	Features []float32 `protobuf:"fixed32,1,rep,packed,name=features,proto3" json:"features,omitempty"`
	// Limit
	Limit uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Continuation token
	ContinuationToken *float32 `protobuf:"fixed32,3,opt,name=continuation_token,json=continuationToken,proto3,oneof" json:"continuation_token,omitempty"`
	// API key to access the service
	ApiKey        string `protobuf:"bytes,4,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVectorsRequest) Reset() {
	*x = QueryVectorsRequest{}
	mi := &file_sse_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVectorsRequest) ProtoMessage() {}

func (x *QueryVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVectorsRequest.ProtoReflect.Descriptor instead.
func (*QueryVectorsRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{8}
}

func (x *QueryVectorsRequest) GetFeatures() []float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *QueryVectorsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QueryVectorsRequest) GetContinuationToken() float32 {
	if x != nil && x.ContinuationToken != nil {
		return *x.ContinuationToken
	}
	return 0
}

func (x *QueryVectorsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// List item for a vector
type VectorListItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the vector
	VectorId uint64 `protobuf:"varint,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	// ID of the media resource
	MediaId uint64 `protobuf:"varint,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	// Data hash
	DataHash      string `protobuf:"bytes,3,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorListItem) Reset() {
	*x = VectorListItem{}
	mi := &file_sse_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorListItem) ProtoMessage() {}

func (x *VectorListItem) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorListItem.ProtoReflect.Descriptor instead.
func (*VectorListItem) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{9}
}

func (x *VectorListItem) GetVectorId() uint64 {
	if x != nil {
		return x.VectorId
	}
	return 0
}

func (x *VectorListItem) GetMediaId() uint64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *VectorListItem) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

// Response with a list of vectors
type VectorListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of vectors
	Vectors []*VectorListItem `protobuf:"bytes,1,rep,name=vectors,proto3" json:"vectors,omitempty"`
	// Continuation token
	ContinuationToken *float32 `protobuf:"fixed32,2,opt,name=continuation_token,json=continuationToken,proto3,oneof" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VectorListResponse) Reset() {
	*x = VectorListResponse{}
	mi := &file_sse_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorListResponse) ProtoMessage() {}

func (x *VectorListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorListResponse.ProtoReflect.Descriptor instead.
func (*VectorListResponse) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{10}
}

func (x *VectorListResponse) GetVectors() []*VectorListItem {
	if x != nil {
		return x.Vectors
	}
	return nil
}

func (x *VectorListResponse) GetContinuationToken() float32 {
	if x != nil && x.ContinuationToken != nil {
		return *x.ContinuationToken
	}
	return 0
}

// Request to insert a vector
type InsertVectorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the media resource
	MediaId uint64 `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	// Data hash
	DataHash string `protobuf:"bytes,2,opt,name=data_hash,json=dataHash,proto3" json:"data_hash,omitempty"`
	// Embedding features
	Features      []float32 `protobuf:"fixed32,3,rep,packed,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertVectorRequest) Reset() {
	*x = InsertVectorRequest{}
	mi := &file_sse_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertVectorRequest) ProtoMessage() {}

func (x *InsertVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertVectorRequest.ProtoReflect.Descriptor instead.
func (*InsertVectorRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{11}
}

func (x *InsertVectorRequest) GetMediaId() uint64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *InsertVectorRequest) GetDataHash() string {
	if x != nil {
		return x.DataHash
	}
	return ""
}

func (x *InsertVectorRequest) GetFeatures() []float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

// Request to insert multiple vectors
type InsertVectorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requests to insert vectors
	Requests []*InsertVectorRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	// API key to access the service
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertVectorsRequest) Reset() {
	*x = InsertVectorsRequest{}
	mi := &file_sse_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertVectorsRequest) ProtoMessage() {}

func (x *InsertVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertVectorsRequest.ProtoReflect.Descriptor instead.
func (*InsertVectorsRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{12}
}

func (x *InsertVectorsRequest) GetRequests() []*InsertVectorRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *InsertVectorsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Request to get the embeddings of a stored vector
type GetVectorEmbeddingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IF od the vector to retrieve embeddings
	VectorId uint64 `protobuf:"varint,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	// API key to access the service
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVectorEmbeddingsRequest) Reset() {
	*x = GetVectorEmbeddingsRequest{}
	mi := &file_sse_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVectorEmbeddingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVectorEmbeddingsRequest) ProtoMessage() {}

func (x *GetVectorEmbeddingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVectorEmbeddingsRequest.ProtoReflect.Descriptor instead.
func (*GetVectorEmbeddingsRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{13}
}

func (x *GetVectorEmbeddingsRequest) GetVectorId() uint64 {
	if x != nil {
		return x.VectorId
	}
	return 0
}

func (x *GetVectorEmbeddingsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Request to delete vectors
type DeleteVectorsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of IDs of vectors to delete
	VectorIds []uint64 `protobuf:"varint,1,rep,packed,name=vector_ids,json=vectorIds,proto3" json:"vector_ids,omitempty"`
	// API key to access the service
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVectorsRequest) Reset() {
	*x = DeleteVectorsRequest{}
	mi := &file_sse_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVectorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVectorsRequest) ProtoMessage() {}

func (x *DeleteVectorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVectorsRequest.ProtoReflect.Descriptor instead.
func (*DeleteVectorsRequest) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteVectorsRequest) GetVectorIds() []uint64 {
	if x != nil {
		return x.VectorIds
	}
	return nil
}

func (x *DeleteVectorsRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

// Empty message for action methods
type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_sse_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sse_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_sse_proto_rawDescGZIP(), []int{15}
}

var File_sse_proto protoreflect.FileDescriptor

const file_sse_proto_rawDesc = "" +
	"\n" +
	"\tsse.proto\x12\apmv.sse\"3\n" +
	"\x18ClipModelMetadataRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"8\n" +
	"\x19ClipModelMetadataResponse\x12\x1b\n" +
	"\tembed_dim\x18\x02 \x01(\rR\bembedDim\"3\n" +
	"\x15ClipEmbeddingResponse\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x02R\bfeatures\"G\n" +
	"\x18ClipTextEmbeddingRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"U\n" +
	"\x1dClipImageEmbeddingRequestInit\x12\x1b\n" +
	"\tmime_type\x18\x01 \x01(\tR\bmimeType\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"A\n" +
	"\x1eClipImageEmbeddingRequestChunk\x12\x1f\n" +
	"\vimage_chunk\x18\x01 \x01(\fR\n" +
	"imageChunk\"\xb3\x01\n" +
	"\x19ClipImageEmbeddingRequest\x12<\n" +
	"\x04init\x18\x01 \x01(\v2&.pmv.sse.ClipImageEmbeddingRequestInitH\x00R\x04init\x12?\n" +
	"\x05chunk\x18\x02 \x01(\v2'.pmv.sse.ClipImageEmbeddingRequestChunkH\x00R\x05chunkB\x17\n" +
	"\x15image_embedding_oneof\"N\n" +
	"\x18GetVectorsByMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x04R\amediaId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\xab\x01\n" +
	"\x13QueryVectorsRequest\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x02R\bfeatures\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x122\n" +
	"\x12continuation_token\x18\x03 \x01(\x02H\x00R\x11continuationToken\x88\x01\x01\x12\x17\n" +
	"\aapi_key\x18\x04 \x01(\tR\x06apiKeyB\x15\n" +
	"\x13_continuation_token\"e\n" +
	"\x0eVectorListItem\x12\x1b\n" +
	"\tvector_id\x18\x01 \x01(\x04R\bvectorId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\x04R\amediaId\x12\x1b\n" +
	"\tdata_hash\x18\x03 \x01(\tR\bdataHash\"\x92\x01\n" +
	"\x12VectorListResponse\x121\n" +
	"\avectors\x18\x01 \x03(\v2\x17.pmv.sse.VectorListItemR\avectors\x122\n" +
	"\x12continuation_token\x18\x02 \x01(\x02H\x00R\x11continuationToken\x88\x01\x01B\x15\n" +
	"\x13_continuation_token\"i\n" +
	"\x13InsertVectorRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x04R\amediaId\x12\x1b\n" +
	"\tdata_hash\x18\x02 \x01(\tR\bdataHash\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\x02R\bfeatures\"i\n" +
	"\x14InsertVectorsRequest\x128\n" +
	"\brequests\x18\x01 \x03(\v2\x1c.pmv.sse.InsertVectorRequestR\brequests\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"R\n" +
	"\x1aGetVectorEmbeddingsRequest\x12\x1b\n" +
	"\tvector_id\x18\x01 \x01(\x04R\bvectorId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"N\n" +
	"\x14DeleteVectorsRequest\x12\x1d\n" +
	"\n" +
	"vector_ids\x18\x01 \x03(\x04R\tvectorIds\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\x0f\n" +
	"\rEmptyResponse2\xaa\x05\n" +
	"\x1bSemanticSearchEngineService\x12Y\n" +
	"\x10GetModelMetadata\x12!.pmv.sse.ClipModelMetadataRequest\x1a\".pmv.sse.ClipModelMetadataResponse\x12O\n" +
	"\n" +
	"EncodeText\x12!.pmv.sse.ClipTextEmbeddingRequest\x1a\x1e.pmv.sse.ClipEmbeddingResponse\x12S\n" +
	"\vEncodeImage\x12\".pmv.sse.ClipImageEmbeddingRequest\x1a\x1e.pmv.sse.ClipEmbeddingResponse(\x01\x12Z\n" +
	"\x13GetVectorEmbeddings\x12#.pmv.sse.GetVectorEmbeddingsRequest\x1a\x1e.pmv.sse.ClipEmbeddingResponse\x12S\n" +
	"\x11GetVectorsByMedia\x12!.pmv.sse.GetVectorsByMediaRequest\x1a\x1b.pmv.sse.VectorListResponse\x12I\n" +
	"\fQueryVectors\x12\x1c.pmv.sse.QueryVectorsRequest\x1a\x1b.pmv.sse.VectorListResponse\x12F\n" +
	"\rInsertVectors\x12\x1d.pmv.sse.InsertVectorsRequest\x1a\x16.pmv.sse.EmptyResponse\x12F\n" +
	"\rDeleteVectors\x12\x1d.pmv.sse.DeleteVectorsRequest\x1a\x16.pmv.sse.EmptyResponseBWZUgithub.com/AgustinSRG/PersonalMediaVault/semantic-search-engine/protocol/sse-proto-gob\x06proto3"

var (
	file_sse_proto_rawDescOnce sync.Once
	file_sse_proto_rawDescData []byte
)

func file_sse_proto_rawDescGZIP() []byte {
	file_sse_proto_rawDescOnce.Do(func() {
		file_sse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sse_proto_rawDesc), len(file_sse_proto_rawDesc)))
	})
	return file_sse_proto_rawDescData
}

var file_sse_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_sse_proto_goTypes = []any{
	(*ClipModelMetadataRequest)(nil),       // 0: pmv.sse.ClipModelMetadataRequest
	(*ClipModelMetadataResponse)(nil),      // 1: pmv.sse.ClipModelMetadataResponse
	(*ClipEmbeddingResponse)(nil),          // 2: pmv.sse.ClipEmbeddingResponse
	(*ClipTextEmbeddingRequest)(nil),       // 3: pmv.sse.ClipTextEmbeddingRequest
	(*ClipImageEmbeddingRequestInit)(nil),  // 4: pmv.sse.ClipImageEmbeddingRequestInit
	(*ClipImageEmbeddingRequestChunk)(nil), // 5: pmv.sse.ClipImageEmbeddingRequestChunk
	(*ClipImageEmbeddingRequest)(nil),      // 6: pmv.sse.ClipImageEmbeddingRequest
	(*GetVectorsByMediaRequest)(nil),       // 7: pmv.sse.GetVectorsByMediaRequest
	(*QueryVectorsRequest)(nil),            // 8: pmv.sse.QueryVectorsRequest
	(*VectorListItem)(nil),                 // 9: pmv.sse.VectorListItem
	(*VectorListResponse)(nil),             // 10: pmv.sse.VectorListResponse
	(*InsertVectorRequest)(nil),            // 11: pmv.sse.InsertVectorRequest
	(*InsertVectorsRequest)(nil),           // 12: pmv.sse.InsertVectorsRequest
	(*GetVectorEmbeddingsRequest)(nil),     // 13: pmv.sse.GetVectorEmbeddingsRequest
	(*DeleteVectorsRequest)(nil),           // 14: pmv.sse.DeleteVectorsRequest
	(*EmptyResponse)(nil),                  // 15: pmv.sse.EmptyResponse
}
var file_sse_proto_depIdxs = []int32{
	4,  // 0: pmv.sse.ClipImageEmbeddingRequest.init:type_name -> pmv.sse.ClipImageEmbeddingRequestInit
	5,  // 1: pmv.sse.ClipImageEmbeddingRequest.chunk:type_name -> pmv.sse.ClipImageEmbeddingRequestChunk
	9,  // 2: pmv.sse.VectorListResponse.vectors:type_name -> pmv.sse.VectorListItem
	11, // 3: pmv.sse.InsertVectorsRequest.requests:type_name -> pmv.sse.InsertVectorRequest
	0,  // 4: pmv.sse.SemanticSearchEngineService.GetModelMetadata:input_type -> pmv.sse.ClipModelMetadataRequest
	3,  // 5: pmv.sse.SemanticSearchEngineService.EncodeText:input_type -> pmv.sse.ClipTextEmbeddingRequest
	6,  // 6: pmv.sse.SemanticSearchEngineService.EncodeImage:input_type -> pmv.sse.ClipImageEmbeddingRequest
	13, // 7: pmv.sse.SemanticSearchEngineService.GetVectorEmbeddings:input_type -> pmv.sse.GetVectorEmbeddingsRequest
	7,  // 8: pmv.sse.SemanticSearchEngineService.GetVectorsByMedia:input_type -> pmv.sse.GetVectorsByMediaRequest
	8,  // 9: pmv.sse.SemanticSearchEngineService.QueryVectors:input_type -> pmv.sse.QueryVectorsRequest
	12, // 10: pmv.sse.SemanticSearchEngineService.InsertVectors:input_type -> pmv.sse.InsertVectorsRequest
	14, // 11: pmv.sse.SemanticSearchEngineService.DeleteVectors:input_type -> pmv.sse.DeleteVectorsRequest
	1,  // 12: pmv.sse.SemanticSearchEngineService.GetModelMetadata:output_type -> pmv.sse.ClipModelMetadataResponse
	2,  // 13: pmv.sse.SemanticSearchEngineService.EncodeText:output_type -> pmv.sse.ClipEmbeddingResponse
	2,  // 14: pmv.sse.SemanticSearchEngineService.EncodeImage:output_type -> pmv.sse.ClipEmbeddingResponse
	2,  // 15: pmv.sse.SemanticSearchEngineService.GetVectorEmbeddings:output_type -> pmv.sse.ClipEmbeddingResponse
	10, // 16: pmv.sse.SemanticSearchEngineService.GetVectorsByMedia:output_type -> pmv.sse.VectorListResponse
	10, // 17: pmv.sse.SemanticSearchEngineService.QueryVectors:output_type -> pmv.sse.VectorListResponse
	15, // 18: pmv.sse.SemanticSearchEngineService.InsertVectors:output_type -> pmv.sse.EmptyResponse
	15, // 19: pmv.sse.SemanticSearchEngineService.DeleteVectors:output_type -> pmv.sse.EmptyResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sse_proto_init() }
func file_sse_proto_init() {
	if File_sse_proto != nil {
		return
	}
	file_sse_proto_msgTypes[6].OneofWrappers = []any{
		(*ClipImageEmbeddingRequest_Init)(nil),
		(*ClipImageEmbeddingRequest_Chunk)(nil),
	}
	file_sse_proto_msgTypes[8].OneofWrappers = []any{}
	file_sse_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sse_proto_rawDesc), len(file_sse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sse_proto_goTypes,
		DependencyIndexes: file_sse_proto_depIdxs,
		MessageInfos:      file_sse_proto_msgTypes,
	}.Build()
	File_sse_proto = out.File
	file_sse_proto_goTypes = nil
	file_sse_proto_depIdxs = nil
}
