// Semantic Search Engine Protocol

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: sse.proto

package sse_proto_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticSearchEngineService_GetModelMetadata_FullMethodName    = "/pmv.sse.SemanticSearchEngineService/GetModelMetadata"
	SemanticSearchEngineService_EncodeText_FullMethodName          = "/pmv.sse.SemanticSearchEngineService/EncodeText"
	SemanticSearchEngineService_EncodeImage_FullMethodName         = "/pmv.sse.SemanticSearchEngineService/EncodeImage"
	SemanticSearchEngineService_GetVectorEmbeddings_FullMethodName = "/pmv.sse.SemanticSearchEngineService/GetVectorEmbeddings"
	SemanticSearchEngineService_GetVectorsByMedia_FullMethodName   = "/pmv.sse.SemanticSearchEngineService/GetVectorsByMedia"
	SemanticSearchEngineService_QueryVectors_FullMethodName        = "/pmv.sse.SemanticSearchEngineService/QueryVectors"
	SemanticSearchEngineService_InsertVectors_FullMethodName       = "/pmv.sse.SemanticSearchEngineService/InsertVectors"
	SemanticSearchEngineService_DeleteVectors_FullMethodName       = "/pmv.sse.SemanticSearchEngineService/DeleteVectors"
)

// SemanticSearchEngineServiceClient is the client API for SemanticSearchEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Semantic search engine service
type SemanticSearchEngineServiceClient interface {
	// Gets model metadata
	GetModelMetadata(ctx context.Context, in *ClipModelMetadataRequest, opts ...grpc.CallOption) (*ClipModelMetadataResponse, error)
	// Encode text
	EncodeText(ctx context.Context, in *ClipTextEmbeddingRequest, opts ...grpc.CallOption) (*ClipEmbeddingResponse, error)
	// Encode image
	EncodeImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClipImageEmbeddingRequest, ClipEmbeddingResponse], error)
	// Get embeddings of stored vector
	GetVectorEmbeddings(ctx context.Context, in *GetVectorEmbeddingsRequest, opts ...grpc.CallOption) (*ClipEmbeddingResponse, error)
	// Get stored vectors by media
	GetVectorsByMedia(ctx context.Context, in *GetVectorsByMediaRequest, opts ...grpc.CallOption) (*VectorListResponse, error)
	// Query vectors sorted by distance
	QueryVectors(ctx context.Context, in *QueryVectorsRequest, opts ...grpc.CallOption) (*VectorListResponse, error)
	// Insert vectors
	InsertVectors(ctx context.Context, in *InsertVectorsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	// Deletes vectors
	DeleteVectors(ctx context.Context, in *DeleteVectorsRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type semanticSearchEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticSearchEngineServiceClient(cc grpc.ClientConnInterface) SemanticSearchEngineServiceClient {
	return &semanticSearchEngineServiceClient{cc}
}

func (c *semanticSearchEngineServiceClient) GetModelMetadata(ctx context.Context, in *ClipModelMetadataRequest, opts ...grpc.CallOption) (*ClipModelMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClipModelMetadataResponse)
	err := c.cc.Invoke(ctx, SemanticSearchEngineService_GetModelMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticSearchEngineServiceClient) EncodeText(ctx context.Context, in *ClipTextEmbeddingRequest, opts ...grpc.CallOption) (*ClipEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClipEmbeddingResponse)
	err := c.cc.Invoke(ctx, SemanticSearchEngineService_EncodeText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticSearchEngineServiceClient) EncodeImage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClipImageEmbeddingRequest, ClipEmbeddingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SemanticSearchEngineService_ServiceDesc.Streams[0], SemanticSearchEngineService_EncodeImage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClipImageEmbeddingRequest, ClipEmbeddingResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SemanticSearchEngineService_EncodeImageClient = grpc.ClientStreamingClient[ClipImageEmbeddingRequest, ClipEmbeddingResponse]

func (c *semanticSearchEngineServiceClient) GetVectorEmbeddings(ctx context.Context, in *GetVectorEmbeddingsRequest, opts ...grpc.CallOption) (*ClipEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClipEmbeddingResponse)
	err := c.cc.Invoke(ctx, SemanticSearchEngineService_GetVectorEmbeddings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticSearchEngineServiceClient) GetVectorsByMedia(ctx context.Context, in *GetVectorsByMediaRequest, opts ...grpc.CallOption) (*VectorListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorListResponse)
	err := c.cc.Invoke(ctx, SemanticSearchEngineService_GetVectorsByMedia_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticSearchEngineServiceClient) QueryVectors(ctx context.Context, in *QueryVectorsRequest, opts ...grpc.CallOption) (*VectorListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorListResponse)
	err := c.cc.Invoke(ctx, SemanticSearchEngineService_QueryVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticSearchEngineServiceClient) InsertVectors(ctx context.Context, in *InsertVectorsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, SemanticSearchEngineService_InsertVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticSearchEngineServiceClient) DeleteVectors(ctx context.Context, in *DeleteVectorsRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, SemanticSearchEngineService_DeleteVectors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticSearchEngineServiceServer is the server API for SemanticSearchEngineService service.
// All implementations must embed UnimplementedSemanticSearchEngineServiceServer
// for forward compatibility.
//
// Semantic search engine service
type SemanticSearchEngineServiceServer interface {
	// Gets model metadata
	GetModelMetadata(context.Context, *ClipModelMetadataRequest) (*ClipModelMetadataResponse, error)
	// Encode text
	EncodeText(context.Context, *ClipTextEmbeddingRequest) (*ClipEmbeddingResponse, error)
	// Encode image
	EncodeImage(grpc.ClientStreamingServer[ClipImageEmbeddingRequest, ClipEmbeddingResponse]) error
	// Get embeddings of stored vector
	GetVectorEmbeddings(context.Context, *GetVectorEmbeddingsRequest) (*ClipEmbeddingResponse, error)
	// Get stored vectors by media
	GetVectorsByMedia(context.Context, *GetVectorsByMediaRequest) (*VectorListResponse, error)
	// Query vectors sorted by distance
	QueryVectors(context.Context, *QueryVectorsRequest) (*VectorListResponse, error)
	// Insert vectors
	InsertVectors(context.Context, *InsertVectorsRequest) (*EmptyResponse, error)
	// Deletes vectors
	DeleteVectors(context.Context, *DeleteVectorsRequest) (*EmptyResponse, error)
	mustEmbedUnimplementedSemanticSearchEngineServiceServer()
}

// UnimplementedSemanticSearchEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticSearchEngineServiceServer struct{}

func (UnimplementedSemanticSearchEngineServiceServer) GetModelMetadata(context.Context, *ClipModelMetadataRequest) (*ClipModelMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModelMetadata not implemented")
}
func (UnimplementedSemanticSearchEngineServiceServer) EncodeText(context.Context, *ClipTextEmbeddingRequest) (*ClipEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncodeText not implemented")
}
func (UnimplementedSemanticSearchEngineServiceServer) EncodeImage(grpc.ClientStreamingServer[ClipImageEmbeddingRequest, ClipEmbeddingResponse]) error {
	return status.Error(codes.Unimplemented, "method EncodeImage not implemented")
}
func (UnimplementedSemanticSearchEngineServiceServer) GetVectorEmbeddings(context.Context, *GetVectorEmbeddingsRequest) (*ClipEmbeddingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVectorEmbeddings not implemented")
}
func (UnimplementedSemanticSearchEngineServiceServer) GetVectorsByMedia(context.Context, *GetVectorsByMediaRequest) (*VectorListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVectorsByMedia not implemented")
}
func (UnimplementedSemanticSearchEngineServiceServer) QueryVectors(context.Context, *QueryVectorsRequest) (*VectorListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryVectors not implemented")
}
func (UnimplementedSemanticSearchEngineServiceServer) InsertVectors(context.Context, *InsertVectorsRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertVectors not implemented")
}
func (UnimplementedSemanticSearchEngineServiceServer) DeleteVectors(context.Context, *DeleteVectorsRequest) (*EmptyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVectors not implemented")
}
func (UnimplementedSemanticSearchEngineServiceServer) mustEmbedUnimplementedSemanticSearchEngineServiceServer() {
}
func (UnimplementedSemanticSearchEngineServiceServer) testEmbeddedByValue() {}

// UnsafeSemanticSearchEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticSearchEngineServiceServer will
// result in compilation errors.
type UnsafeSemanticSearchEngineServiceServer interface {
	mustEmbedUnimplementedSemanticSearchEngineServiceServer()
}

func RegisterSemanticSearchEngineServiceServer(s grpc.ServiceRegistrar, srv SemanticSearchEngineServiceServer) {
	// If the following call panics, it indicates UnimplementedSemanticSearchEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticSearchEngineService_ServiceDesc, srv)
}

func _SemanticSearchEngineService_GetModelMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipModelMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchEngineServiceServer).GetModelMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchEngineService_GetModelMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchEngineServiceServer).GetModelMetadata(ctx, req.(*ClipModelMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticSearchEngineService_EncodeText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipTextEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchEngineServiceServer).EncodeText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchEngineService_EncodeText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchEngineServiceServer).EncodeText(ctx, req.(*ClipTextEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticSearchEngineService_EncodeImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SemanticSearchEngineServiceServer).EncodeImage(&grpc.GenericServerStream[ClipImageEmbeddingRequest, ClipEmbeddingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SemanticSearchEngineService_EncodeImageServer = grpc.ClientStreamingServer[ClipImageEmbeddingRequest, ClipEmbeddingResponse]

func _SemanticSearchEngineService_GetVectorEmbeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVectorEmbeddingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchEngineServiceServer).GetVectorEmbeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchEngineService_GetVectorEmbeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchEngineServiceServer).GetVectorEmbeddings(ctx, req.(*GetVectorEmbeddingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticSearchEngineService_GetVectorsByMedia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVectorsByMediaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchEngineServiceServer).GetVectorsByMedia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchEngineService_GetVectorsByMedia_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchEngineServiceServer).GetVectorsByMedia(ctx, req.(*GetVectorsByMediaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticSearchEngineService_QueryVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchEngineServiceServer).QueryVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchEngineService_QueryVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchEngineServiceServer).QueryVectors(ctx, req.(*QueryVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticSearchEngineService_InsertVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchEngineServiceServer).InsertVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchEngineService_InsertVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchEngineServiceServer).InsertVectors(ctx, req.(*InsertVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticSearchEngineService_DeleteVectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVectorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticSearchEngineServiceServer).DeleteVectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticSearchEngineService_DeleteVectors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticSearchEngineServiceServer).DeleteVectors(ctx, req.(*DeleteVectorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticSearchEngineService_ServiceDesc is the grpc.ServiceDesc for SemanticSearchEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticSearchEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pmv.sse.SemanticSearchEngineService",
	HandlerType: (*SemanticSearchEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModelMetadata",
			Handler:    _SemanticSearchEngineService_GetModelMetadata_Handler,
		},
		{
			MethodName: "EncodeText",
			Handler:    _SemanticSearchEngineService_EncodeText_Handler,
		},
		{
			MethodName: "GetVectorEmbeddings",
			Handler:    _SemanticSearchEngineService_GetVectorEmbeddings_Handler,
		},
		{
			MethodName: "GetVectorsByMedia",
			Handler:    _SemanticSearchEngineService_GetVectorsByMedia_Handler,
		},
		{
			MethodName: "QueryVectors",
			Handler:    _SemanticSearchEngineService_QueryVectors_Handler,
		},
		{
			MethodName: "InsertVectors",
			Handler:    _SemanticSearchEngineService_InsertVectors_Handler,
		},
		{
			MethodName: "DeleteVectors",
			Handler:    _SemanticSearchEngineService_DeleteVectors_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EncodeImage",
			Handler:       _SemanticSearchEngineService_EncodeImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sse.proto",
}
