name: Backend

on:
  push:
    branches: [ "master" ]
    paths:
      - backend/**
      - .github/workflows/backend.yml
  pull_request:
    branches: [ "master" ]
    paths:
      - backend/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: 1.25.x

    - name: Set up ffmpeg 
      id: ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: release

    - name: Build
      working-directory: ./backend
      run: go build -v ./...

    - name: Test
      working-directory: ./backend
      run: go test -v ./...
      env:
        FFMPEG_PATH: ${{ steps.ffmpeg.outputs.ffmpeg-path }}/ffmpeg
        FFPROBE_PATH: ${{ steps.ffmpeg.outputs.ffmpeg-path }}/ffprobe
