name: Backend (Go) CI

on:
  push:
    branches: [ "master" ]
    paths:
      - backend/**
      - .github/workflows/**
  pull_request:
    branches: [ "master" ]
    paths:
      - backend/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - name: Set up ffmpeg 
      uses: FedericoCarboni/setup-ffmpeg@v2

    - run: cd backend

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
