name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set env RELEASE_VERSION
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build VueJS frontend
      working-directory: ./frontend
      run: npm install --no-optional && npm run build

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag asanrom/pmv:latest
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: asanrom
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Add version tag to Docker image
      run: docker tag asanrom/pmv:latest asanrom/pmv:${{ env.RELEASE_VERSION }}
      
    - name: Push the Docker image (Current Version)
      run: docker push asanrom/pmv:${{ env.RELEASE_VERSION }}
        
    - name: Push the Docker image (Latest)
      run: docker push asanrom/pmv:latest
    
    - name: Docker Login (GitHub Packages)
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag version (GitHub Packages)
      run: docker tag asanrom/pmv:latest ghcr.io/agustinsrg/personalmediavault:${{ env.RELEASE_VERSION }}

    - name: Tag latest (GitHub Packages)
      run: docker tag asanrom/pmv:latest ghcr.io/agustinsrg/personalmediavault:latest

    - name: Push the Docker image (GitHub Packages) (Current Version)
      run: docker push ghcr.io/agustinsrg/personalmediavault:${{ env.RELEASE_VERSION }}
        
    - name: Push the Docker image (GitHub Packages) (Latest)
      run: docker push ghcr.io/agustinsrg/personalmediavault:latest
    
