name: Launcher (Go) CI

on:
  push:
    branches: [ "master" ]
    paths:
      - launcher/**
  pull_request:
    branches: [ "master" ]
    paths:
      - launcher/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - run: cd launcher

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
